development:
  database: saasbase_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: saasbase_test
  pool: 5
  host: localhost

production:
  database: saasbase_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres
