development:
  adapter: postgresql
  encoding: unicode
  database: saasbase_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: saasbase_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
