development:
  database: saasbase_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres


test:
  adapter: postgresql
  encoding: unicode
  database: saasbase_test
  pool: 5
  host: localhost

production:
  database: ENV['database_url']
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: ENV['database_username']
  password: ENV['database_password']
